name: Main CI
on: [workflow_dispatch, push]
jobs:
  tests_checks_build_deploy:
    runs-on: ubuntu-latest
    name: Tests, checks, build
    steps:
      - uses: actions/checkout@v5
        name: Checkout
      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: "npm"
        name: Setup node
      - name: Install dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint
      - name: Run tests
        run: npm run test:ci
      - name: Run build
        run: npm run build
      - name: Deploy to gh-pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
