name: Main CI
on: [workflow_dispatch, push]
jobs:
  tests_checks_build:
    runs-on: ubuntu-latest
    name: Tests, checks, build
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - name: Install dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint
      - name: Run tests
        run: npm run test:ci
      - name: Run build
        run: npm run build
